### ISSUE TITLE
[1.15.2] Mod does not load the config file from the defaultconfig folder

### ISSUE THREAD

**Issue by realTIMematrix** [Squidsword/Ores-Above-Diamonds#3]
Hi,

I'm using:

Minecraft: 1.15.2
Forge: 31.0.1
OresAboveDiamonds+1.15+v2.1.jar

i recognized that your mod generates two different .toml files. but the .toml file which is later in the config folder (oresabovediamonds.toml) will not be loaded if it is in the defaultconfig folder. Only your oresabovediamonds-server.toml works as expected and will be loaded from the defaultconfig folder for new games.

**Comment by Squidsword** [comment]
Hey realITIMematrix,

Thank you for bringing this up. I am inexperienced with this issue and I am not sure how to fix it. For me, I only get one config file generated in the config folder rather than a separate server config file. In the code, there's only a single server-sided file because none of the configurations are client-side so I figured it would do. I tested it client-wise and it still works, however it only updates to freshly generated chunks as there is no retrogen support for this mod. I am a beginner programmer so I may be missing something. Please let me know if so.

I am also not familiar with the defaultconfig folder.

I apologize for any inconvenience.

**Comment by realTIMematrix** [comment]
Hi,

I'm not familiar with coding at all, i can only tell you what i see in the log file. With other mods that worked fine like the [guidebook mod from gigaherz](https://www.curseforge.com/minecraft/mc-mods/guidebook). His mod creates a gbook-client.toml and gbook-server.toml which can me moved later (once created) to the defaultconfig folder within the instance and if i delete the config folder all config files will be loaded from defaultconfig folder after a fresh start (which is very, very good for modpack testing)

**Comment by Squidsword** [comment]
Thank you for the information and the example, I'll look into it and I'll get back to you.

**Comment by Squidsword** [comment]
Hey, I've pushed an update where I revamped the config file completely in v3.0. It might have fixed your issue. If you decide to test it out, let me know if it works or not. Have a good one. 

(It'll be visible as soon as the curseforge mods approve it.)

**Comment by Squidsword** [comment]
I pushed another patch around 2-3 days ago that might have fixed it. Other mod developers had the same problem and they did a similar fix that solved the issue, so this fix may seem more promising than the last. Please feel free to contact me again or open an issue if the problem still persists. Have a good one.
